# Generated by Django 5.2.1 on 2025-05-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', 'fix_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Định danh của cấu hình (vd: openrouter_api_key, teams_webhook_ba)', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Giá trị của cấu hình')),
                ('key_type', models.CharField(choices=[('api_key', 'API Key'), ('webhook', 'Webhook URL'), ('other', 'Other')], default='other', max_length=20)),
                ('team', models.CharField(blank=True, choices=[('dev', 'Developer'), ('system', 'System Admin'), ('ba', 'Business Analyst'), ('tester', 'Tester')], help_text='Team áp dụng (nếu cấu hình dành riêng cho team)', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả về cấu hình')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
                'ordering': ['key'],
            },
        ),
    ]
