# Generated by Django 5.2.1 on 2025-05-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('api', 'API Endpoint'), ('rss', 'RSS Feed'), ('static', 'Web Tĩnh (AgentQL)')], max_length=10)),
                ('team', models.CharField(choices=[('dev', 'Developer'), ('system', 'System'), ('ba', 'Business Analyst')], max_length=10)),
                ('content_type', models.IntegerField(choices=[(1, 'Kinh tế/Tài chính'), (2, 'YouTube/Social Media'), (3, 'Công nghệ'), (4, 'Tin tức tổng hợp')], default=4)),
                ('params', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetch_interval', models.IntegerField(default=3600, help_text='Interval in seconds')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nguồn dữ liệu',
                'verbose_name_plural': 'Nguồn dữ liệu',
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('error', 'Lỗi'), ('partial', 'Một phần')], max_length=10)),
                ('articles_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(help_text='Time in seconds')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='collector.source')),
            ],
            options={
                'verbose_name': 'Log thu thập',
                'verbose_name_plural': 'Log thu thập',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('content_type', models.IntegerField(choices=[(1, 'Kinh tế/Tài chính'), (2, 'YouTube/Social Media'), (3, 'Công nghệ'), (4, 'Tin tức tổng hợp')])),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('content', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='collector.source')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at'],
            },
        ),
    ]
