# Generated by Django 5.2.1 on 2025-05-30 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('error', 'Lỗi')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log AI (OpenRouter)',
                'verbose_name_plural': 'Log AI (OpenRouter)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('crawl', 'Cào dữ liệu'), ('openrouter', 'Gửi OpenRouter')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('limit', models.IntegerField(default=10)),
                ('round_robin_types', models.JSONField(blank=True, default=list)),
                ('last_type_sent', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Job Config',
                'verbose_name_plural': 'Job Configs',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('api', 'API Endpoint'), ('rss', 'RSS Feed'), ('static', 'Web Tĩnh (AgentQL)')], max_length=10)),
                ('content_type', models.IntegerField(choices=[(1, 'Kinh tế/Tài chính'), (2, 'YouTube/Social Media'), (3, 'Công nghệ'), (4, 'Tin tức tổng hợp')], default=4)),
                ('params', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fetch_interval', models.IntegerField(default=3600, help_text='Interval in seconds')),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('force_collect', models.BooleanField(default=False, help_text='Bật để luôn thu thập nguồn này, bỏ qua thời gian chờ')),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã code của team (ví dụ: dev, ba, system)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Tên đầy đủ của team', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Mô tả về team')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('error', 'Lỗi'), ('partial', 'Một phần')], max_length=10)),
                ('articles_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time', models.FloatField(help_text='Time in seconds')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='collector.source')),
            ],
            options={
                'verbose_name': 'Fetch Log',
                'verbose_name_plural': 'Fetch Logs',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('content_type', models.IntegerField(choices=[(1, 'Kinh tế/Tài chính'), (2, 'YouTube/Social Media'), (3, 'Công nghệ'), (4, 'Tin tức tổng hợp')], default=4)),
                ('published_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('is_ai_processed', models.BooleanField(default=False)),
                ('ai_type', models.CharField(blank=True, max_length=10)),
                ('ai_content', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='collector.source')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('openrouter_api_key', 'OpenRouter API Key'), ('teams_webhook', 'Teams Webhook URL')], help_text='Chọn loại cấu hình cần thiết lập', max_length=100)),
                ('value', models.TextField(help_text='Nhập giá trị cấu hình (API key hoặc webhook URL)')),
                ('key_type', models.CharField(choices=[('api_key', 'API Key'), ('webhook', 'Webhook URL')], max_length=20)),
                ('team', models.CharField(blank=True, choices=[('dev', 'Developer'), ('system', 'System Admin'), ('ba', 'Business Analyst')], help_text='Chọn team (chỉ áp dụng cho Teams Webhook)', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả về cấu hình')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Config',
                'verbose_name_plural': 'System Configs',
                'ordering': ['key'],
                'unique_together': {('key', 'team')},
            },
        ),
        migrations.AddField(
            model_name='source',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='collector.team'),
        ),
    ]
