# Generated by Django 5.2.1 on 2025-05-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('source', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('api', 'API Endpoint'), ('static', 'Web Tĩnh')], max_length=10)),
                ('team', models.CharField(choices=[('dev', 'Developer'), ('system', 'System'), ('ba', 'Business Analyst')], max_length=10)),
                ('params', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
