# Generated by Django 5.2.1 on 2025-05-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('prompt', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('success', 'Thành công'), ('error', 'Lỗi')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log AI (OpenRouter)',
                'verbose_name_plural': 'Log AI (OpenRouter)',
                'ordering': ['-created_at'],
            },
        ),
    ]
