# Generated by Django 5.2.1 on 2025-05-30 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_systemconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='fetchlog',
            options={'ordering': ['-fetched_at'], 'verbose_name': 'Fetch Log', 'verbose_name_plural': 'Fetch Logs'},
        ),
        migrations.AlterModelOptions(
            name='jobconfig',
            options={'verbose_name': 'Job Config', 'verbose_name_plural': 'Job Configs'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['source'], 'verbose_name': 'Data Source', 'verbose_name_plural': 'Data Sources'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'ordering': ['key'], 'verbose_name': 'System Config', 'verbose_name_plural': 'System Configs'},
        ),
    ]
