# Generated by Django 5.2.1 on 2025-05-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_article_options_alter_fetchlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(choices=[('openrouter_api_key', 'OpenRouter API Key'), ('teams_webhook', 'Teams Webhook URL')], help_text='Chọn loại cấu hình cần thiết lập', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key_type',
            field=models.CharField(choices=[('api_key', 'API Key'), ('webhook', 'Webhook URL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='team',
            field=models.CharField(blank=True, choices=[('dev', 'Developer'), ('system', 'System Admin'), ('ba', 'Business Analyst')], help_text='Chọn team (chỉ áp dụng cho Teams Webhook)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.TextField(help_text='Nhập giá trị cấu hình (API key hoặc webhook URL)'),
        ),
        migrations.AlterUniqueTogether(
            name='systemconfig',
            unique_together={('key', 'team')},
        ),
    ]
