# Generated by Django 5.2.1 on 2025-05-26 03:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_update_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Nguồn dữ liệu', 'verbose_name_plural': 'Nguồn dữ liệu'},
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
