# Generated by Django 5.2.1 on 2025-05-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_ailog'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='force_collect',
            field=models.BooleanField(default=False, help_text='Bật để luôn thu thập nguồn này, bỏ qua thời gian chờ'),
        ),
    ]
