# Generated by Django 5.2.1 on 2025-05-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_systemconfig_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='ailog',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='collector.article'),
        ),
    ]
