# Generated by Django 5.2.1 on 2025-05-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_source_force_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('crawl', 'Cào dữ liệu'), ('openrouter', 'Gửi OpenRouter')], max_length=50, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('interval', models.IntegerField(default=300)),
                ('limit', models.IntegerField(default=10)),
                ('round_robin_types', models.JSONField(blank=True, default=list)),
                ('last_type_sent', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='ai_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='ai_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='is_ai_processed',
            field=models.BooleanField(default=False),
        ),
    ]
