# Generated by Django 5.2.1 on 2025-06-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_ailog_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ailog',
            name='article',
        ),
    ]
