# Generated by Django 5.2.1 on 2025-06-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0004_remove_ailog_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='content_type',
        ),
    ]
