# Generated by Django 5.2.1 on 2025-06-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_remove_article_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(choices=[('openrouter_api_key', 'OpenRouter API Key'), ('teams_webhook', 'Teams Webhook URL'), ('agentql_api_key', 'AgentQL API Key')], help_text='Chọn loại cấu hình cần thiết lập', max_length=100),
        ),
    ]
