# Generated by Django 5.2.1 on 2025-05-29 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_remove_interval_from_jobconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['source'], 'verbose_name': 'Nguồn dữ liệu', 'verbose_name_plural': 'Nguồn dữ liệu'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='fetched_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='ai_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='ai_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_type',
            field=models.IntegerField(choices=[(1, 'Kinh tế/Tài chính'), (2, 'YouTube/Social Media'), (3, 'Công nghệ'), (4, 'Tin tức tổng hợp')], default=4),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
